# Generated by Django 4.1 on 2024-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_dish_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('W', 'West Campus'), ('E', 'East Campus'), ('O', 'Other places'), ('J', 'Jinzhai Road'), ('H', 'Huangshan Road')], default='O', max_length=1),
        ),
    ]
