# Generated by Django 4.1 on 2024-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_restaurant_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='AVG_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
